#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["JobOffersPortal.API/JobOffersPortal.API.csproj", "JobOffersPortal.API/"]
COPY ["JobOffersPortal.Application/JobOffersPortal.Application.csproj", "JobOffersPortal.Application/"]
COPY ["JobOffersPortal.Domain/JobOffersPortal.Domain.csproj", "JobOffersPortal.Domain/"]
COPY ["JobOffersPortal.Infrastructure/JobOffersPortal.Persistance.EF.csproj", "JobOffersPortal.Infrastructure/"]
COPY ["JobOffersPortal.Application.Security/JobOffersPortal.Application.Security.csproj", "JobOffersPortal.Application.Security/"]
COPY ["JobOffersPortal.Infrastructure.Security/JobOffersPortal.Infrastructure.Security.csproj", "JobOffersPortal.Infrastructure.Security/"]
RUN dotnet restore "JobOffersPortal.API/JobOffersPortal.API.csproj"
COPY . .
WORKDIR "/src/JobOffersPortal.API"
RUN dotnet build "JobOffersPortal.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "JobOffersPortal.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "JobOffersPortal.API.dll"]